
#define UART_RX_BUF_SIZE  64
#define UART_TX_BUF_SIZE  64

#define UART_BAUDRATE  38400
#define UART_BSCALE  0

// AX-12
#define UARTC1_ENABLED
#define UARTC1_BAUDRATE  19200
// Communication
#define UARTF0_ENABLED
// Cam
#define UARTF1_ENABLED
#define UARTF1_BAUDRATE  38400


#define UART_INTLVL  INTLVL_HI

