#ifndef SENSR_CONFIG_H
#define SENSR_CONFIG_H

//soft
#define SENSOR_FAN_PWM_FREQUENCY 20000

#define SENSOR_B0_FAN_PWM_BURST     20000
#define SENSOR_B0_FAN_PWM_RUN        5000
#define SENSOR_B0_FAN_BURST_DELAY    2000

#define SENSOR_B1_FAN_PWM_BURST     32767
#define SENSOR_B1_FAN_PWM_RUN       32767
#define SENSOR_B1_FAN_BURST_DELAY    2000

#define SENSOR_B2_FAN_PWM_BURST     32767
#define SENSOR_B2_FAN_PWM_RUN       32767
#define SENSOR_B2_FAN_BURST_DELAY    2000



//hard
#define SENSOR_TOP_MOTOR_ENABLE_PORT  PORTD
#define SENSOR_TOP_SENSOR_ENABLE_PORT PORTC
#define SENSOR_TOP_MOTOR_ENABLE_PIN   0
#define SENSOR_TOP_SENSOR_ENABLE_PIN  2

#endif// SENSOR_CONFIG_H
