#ifndef _AUDIO_AMPLIFIER_CONFIG_H_
#define _AUDIO_AMPLIFIER_CONFIG_H_

#define AMPLI_GAIN_0_PP   PORTPIN(A,6)
#define AMPLI_GAIN_1_PP   PORTPIN(A,4)
#define AMPLI_MUTE_PP     PORTPIN(A,7)
#define AMPLI_SHUTDOWN_PP PORTPIN(B,0)


#endif//_AUDIO_AMPLIFIER_CONFIG_H_
