typedef enum {
  TRACK_MUSICS_FRENCH_TRAIN_REMIX_SNCF_BY_JAUGS = 6,
  TRACK_MUSICS_ZELDA_LOW_HEALTH = 23,
  TRACK_SOUNDS_AOL_SIGN_ON_DIAL_UP = 8,
  TRACK_SOUNDS_BASEBALL_CHARGE_ORGAN = 11,
  TRACK_SOUNDS_DUCK_HUNT_LAUGH = 4,
  TRACK_SOUNDS_FINAL_FANTASY_VII_VICTORY_FANFARE = 10,
  TRACK_SOUNDS_LE_CRI_DE_WILHELM = 7,
  TRACK_SOUNDS_LES_MINIONS_PAPUCHE_QUOI_FESSES = 9,
  TRACK_SOUNDS_MARIO_KART_COUNTDOWN = 6,
  TRACK_SOUNDS_METAL_GEAR_SOLID_ALERT = 3,
  TRACK_SOUNDS_ZELDA_SECRET_FOUND = 5,
} track_num_t;

