
#define UART_RX_BUF_SIZE  250
#define UART_TX_BUF_SIZE  250

#define UART_BAUDRATE  38400
#define UART_BSCALE  0

// Communication
#define UARTC1_ENABLED
#define UARTC1_RX_BUF_SIZE  250
#define UARTC1_TX_BUF_SIZE  64


#define UART_INTLVL  INTLVL_MED

