
#define UART_RX_BUF_SIZE  250
#define UART_TX_BUF_SIZE  250

#define UART_BAUDRATE  38400
#define UART_BSCALE  0

// Communication
#define UARTC0_ENABLED
#define UARTC0_RX_BUF_SIZE  250
#define UARTC0_TX_BUF_SIZE  64


#define UART_INTLVL  INTLVL_HI

